language: python

python:
  - 2.7

git:
  depth: 3

install:
  - cd python2
  - pip install -r requirements.txt
  - pip install flake8

script:
  - make && sudo make install-py2
  - hap examples/sample.json --verbose --no-cache
  - hap examples/pattern.json --verbose --no-cache
