matrix:
  include:

    - language: python
      python:
        - 2.7

      git:
        depth: 3

      install:
        - pip install -r python2/requirements.txt
        - pip install flake8

      script:
        - make && sudo make install-py2
        - hap examples/sample.json --verbose --no-cache
        - hap examples/pattern.json --verbose --no-cache

    - language: python
      python:
        - 3.5

      git:
        depth: 3

      install:
        - pip install -r python3/requirements.txt
        - pip install flake8

      script:
        - make && sudo make install-py3
        - hap examples/sample.json --verbose --no-cache
        - hap examples/pattern.json --verbose --no-cache
