sudo: true
dist: "trusty"

matrix:
  include:

    - language: python
      python:
        - 2.7

      git:
        depth: 3

      install:
        - pip install -r python2/requirements.txt
        - pip install flake8
        - pip install -U pip setuptools

      script:
        - make lint-py2 && make test-py2
        - sudo make install-py2
        - hap examples/sample.json --verbose --no-cache
        - hap examples/pattern.json --verbose --no-cache

    - language: python
      python:
        - 3.5

      git:
        depth: 3

      install:
        - sudo apt-get install python3-pip python3-setuptools
        - pip3 install -r python3/requirements.txt
        - pip3 install flake8
        - pip3 install -U pip setuptools

      script:
        - make lint-py3 && make test-py3
        - sudo make install-py3
        - hap examples/sample.json --verbose --no-cache
        - hap examples/pattern.json --verbose --no-cache
