sudo: true
dist: "trusty"

matrix:
  include:

    - language: python
      python:
        - 2.7

      git:
        depth: 3

      install:
        - pip install -r python2/requirements.txt
        - pip install flake8
        - pip install -U pip setuptools

      before_script:
        - flake8 python2/hap
        - python -m unittest discover -v python2/tests
        - python python2/setup.py install

      script:
        - hap examples/sample.json --verbose --no-cache
        - hap examples/pattern.json --verbose --no-cache

    - language: python
      python:
        - 3.5

      git:
        depth: 3

      install:
        - pip3 install -r python3/requirements.txt
        - pip3 install flake8
        - pip3 install -U pip setuptools

      before_script:
        - flake8 python3/hap
        - python -m unittest discover -v python3/tests
        - python python3/setup.py install

      script:
        - hap examples/sample.json --verbose --no-cache
        - hap examples/pattern.json --verbose --no-cache
