sudo: true
dist: "trusty"

matrix:
  include:

    - language: python
      python:
        - 2.7

      git:
        depth: 3

      install:
        - pip install -r python2/requirements.txt
        - pip install flake8
        - pip install -U pip setuptools

      before_script:
        - cd python2
        - flake8 hap
        - python -m unittest discover -v tests
        - python setup.py install

      script:
        - hap examples/sample.json --verbose --no-cache
        - hap examples/pattern.json --verbose --no-cache

    - language: python
      python:
        - 3.5

      git:
        depth: 3

      install:
        - pip install -r python3/requirements.txt
        - pip install flake8
        - pip install -U pip setuptools

      before_script:
        - cd python3
        - flake8 hap
        - python -m unittest discover -v tests
        - python setup.py install

      script:
        - hap examples/sample.json --verbose --no-cache
        - hap examples/pattern.json --verbose --no-cache
