language: python

python:
  - 2.7

git:
  depth: 3

install:
  - pip install -r requirements.txt
  - pip install flake8

script:
  - make && sudo make install
  - hap samples/sample.json --verbose --no-cache
  - hap samples/pattern.json --verbose --no-cache
